import { useEffect, useState } from "react";
import Head from "next/head";
import axios from "axios";

export default function Home() {
  let offset = 0;
  const [pokemon, setPokemon] = useState([]);

  const loadMorePokemon = () => {
    axios
      .get(`https://pokeapi.co/api/v2/pokemon?limit=10&offset=${offset}`)
      .then(({ data }) => {
        const newPokemon = [];
        data.results.forEach((item) => newPokemon.push(item.name));
        setPokemon((oldPokemon)=>[...oldPokemon, ...newPokemon]);
      });

    offset += 10;
  };

  const handleScroll = (e) => {
    const scrollHeight = e.target.documentElement.scrollHeight;
    const currentHeight = Math.ceil(
      e.target.documentElement.scrollTop + window.innerHeight
    );

    if (currentHeight + 1 >= scrollHeight) {
      loadMorePokemon();
    }
  };

  useEffect(() => {
    loadMorePokemon();
    window.addEventListener("scroll", handleScroll);
  }, []);

  return (
    <main>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>
        {pokemon.map((pok, index) => {
          return (
            <div key={index} className="box">
              {index}-{pok}
            </div>
          );
        })}
      </div>
    </main>
  );
}
